import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('--- Cleaning existing database tables ---');
  await prisma.wishlistItem.deleteMany();
  await prisma.cartItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();
  await prisma.user.deleteMany();

  console.log('--- Seeding Users ---');
  const adminPassword = await bcrypt.hash('AdminPassword123!', 10);
  const customerPassword = await bcrypt.hash('CustomerPassword123!', 10);

  const admin = await prisma.user.create({
    data: {
      name: 'Syeda Fatima Zahra',
      email: 'admin@rivaayat.pk',
      password: adminPassword,
      role: 'admin',
      phone: '+92 300 1234567',
      address: 'Suite 401, Clifton Block 4',
      city: 'Karachi',
    },
  });

  const customer1 = await prisma.user.create({
    data: {
      name: 'Ayesha Khan',
      email: 'ayesha.khan@example.com',
      password: customerPassword,
      role: 'customer',
      phone: '+92 321 9876543',
      address: 'House 42, Street 15, Sector F-7/2',
      city: 'Islamabad',
    },
  });

  const customer2 = await prisma.user.create({
    data: {
      name: 'Mahnoor Tariq',
      email: 'mahnoor.tariq@example.com',
      password: customerPassword,
      role: 'customer',
      phone: '+92 333 4567890',
      address: '28-C, Model Town Extension',
      city: 'Lahore',
    },
  });

  console.log('--- Seeding Categories ---');
  const categoriesData = [
    {
      name: 'Casual Sarees',
      slug: 'casual',
      description: 'Effortless lightweight cotton, linen, and georgette drapes for everyday understated elegance.',
      image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    },
    {
      name: 'Work Wear',
      slug: 'work',
      description: 'Sophisticated, breathable and structured sarees designed for boardroom poise and smart elegance.',
      image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
    },
    {
      name: 'Wedding Sarees',
      slug: 'wedding',
      description: 'Opulent banarasi, pure silk, and zari drapes curated for Pakistani wedding celebrations.',
      image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
    },
    {
      name: 'Party Wear',
      slug: 'party-wear',
      description: 'Glamorous chiffon, georgette, and sequin-embellished sarees for soirées and evening dinners.',
      image: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=800&q=80',
    },
    {
      name: 'Festive Collection',
      slug: 'festive',
      description: 'Vibrant hues, tilla borders, and gota work for Eid, Diwali, and festive family gatherings.',
      image: 'https://images.unsplash.com/photo-1610030469668-935a8df2aef6?auto=format&fit=crop&w=800&q=80',
    },
    {
      name: 'Luxury/Bridal',
      slug: 'bridal',
      description: 'Heirloom bridal couture, pure katan silks, hand-crafted zardozi, and resham needlework.',
      image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80',
    },
    {
      name: 'New Arrivals',
      slug: 'new-arrivals',
      description: 'Discover the freshest seasonal releases from the Rivaayat couture design atelier.',
      image: 'https://images.unsplash.com/photo-1610030470298-0c6f2a87895e?auto=format&fit=crop&w=800&q=80',
    },
    {
      name: 'Sale',
      slug: 'sale',
      description: 'Special seasonal privileges and limited archival designs at exclusive prices.',
      image: 'https://images.unsplash.com/photo-1583391733975-081014e7a83d?auto=format&fit=crop&w=800&q=80',
    },
  ];

  const createdCategories: Record<string, string> = {};
  for (const cat of categoriesData) {
    const created = await prisma.category.create({
      data: cat,
    });
    createdCategories[cat.slug] = created.id;
  }

  console.log('--- Seeding 20 Products ---');
  const products = [
    {
      name: 'Shahzadi Crimson Banarasi Pure Silk Saree',
      slug: 'shahzadi-crimson-banarasi-pure-silk-saree',
      description: 'An ode to Mughal grandeur, this heirloom Crimson Banarasi saree is woven from 100% pure katan silk. Intricately finished with real gold zari floral jaal, heavy pallu, and ornate borders. Comes with an unstitched brocade blouse piece.',
      categorySlug: 'wedding',
      price: 48500,
      discountPrice: 42000,
      colors: ['Maroon', 'Red', 'Gold'],
      fabric: 'Pure Katan Banarasi Silk',
      images: [
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 6,
      sku: 'RIV-BAN-001',
      featured: true,
      newArrival: true,
      careGuide: 'Dry Clean Only. Store wrapped in pure muslin cloth. Avoid spraying perfumes directly on zari.',
      blouseDetails: 'Includes 1.0 meter unstitched matching pure silk brocade blouse fabric.',
    },
    {
      name: 'Noor-e-Jahan Emerald Hand-Embroidered Organza Saree',
      slug: 'noor-e-jahan-emerald-hand-embroidered-organza-saree',
      description: 'Delicate sheer organza in deep jewel emerald green, adorned with hand-carved cutdana, resham florets, and scalloped tilla borders. A breathtaking piece for regal evening receptions.',
      categorySlug: 'wedding',
      price: 36000,
      discountPrice: null,
      colors: ['Green', 'Gold'],
      fabric: 'Pure Silk Organza',
      images: [
        'https://images.unsplash.com/photo-1610030469668-935a8df2aef6?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 8,
      sku: 'RIV-ORG-002',
      featured: true,
      newArrival: false,
      careGuide: 'Professional dry clean only. Steam iron on reverse under gentle heat.',
      blouseDetails: 'Includes 0.9m raw silk embroidered blouse piece.',
    },
    {
      name: 'Shab-e-Mehtab Midnight Black Chiffon Tilla Saree',
      slug: 'shab-e-mehtab-midnight-black-chiffon-tilla-saree',
      description: 'Glistening metallic antique gold tilla threadwork over feather-soft midnight black pure chiffon. Drapes with fluid grace and pairs exquisitely with statement earrings for black-tie soirées.',
      categorySlug: 'party-wear',
      price: 16500,
      discountPrice: 14500,
      colors: ['Black', 'Gold'],
      fabric: 'Pure Bamboo Chiffon',
      images: [
        'https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1610030470298-0c6f2a87895e?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 12,
      sku: 'RIV-CHF-003',
      featured: true,
      newArrival: true,
      careGuide: 'Gentle dry clean only. Do not machine wash.',
      blouseDetails: 'Includes 1 meter tonal black silk blouse with matching cuff embellishments.',
    },
    {
      name: 'Falaknuma Ivory Pearl Pure Katan Silk Saree',
      slug: 'falaknuma-ivory-pearl-pure-katan-silk-saree',
      description: 'Epitome of timeless minimalism, this ivory katan saree is elevated with subtle champagne gold badla motifs and a hand-knotted fringe pallu. Quintessential South Asian quiet luxury.',
      categorySlug: 'festive',
      price: 24500,
      discountPrice: 22000,
      colors: ['White', 'Beige', 'Gold'],
      fabric: 'Pure Katan Silk',
      images: [
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1583391733975-081014e7a83d?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 5,
      sku: 'RIV-SLK-004',
      featured: true,
      newArrival: false,
      careGuide: 'Dry clean only. Roll on wooden hanger.',
      blouseDetails: '1.0 meter ivory tissue silk blouse piece included.',
    },
    {
      name: 'Rani Bagh Maroon Velvet Embroidered Bridal Saree',
      slug: 'rani-bagh-maroon-velvet-embroidered-bridal-saree',
      description: 'Crafted for winter brides, featuring plush micro-velvet adorned with handcrafted zardozi, dabka, and pearl work along the pallu and border. Rich, regal, and deeply photogenic.',
      categorySlug: 'bridal',
      price: 78000,
      discountPrice: null,
      colors: ['Maroon', 'Gold'],
      fabric: 'Micro Velvet & Silk Organza',
      images: [
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 3,
      sku: 'RIV-VLV-005',
      featured: true,
      newArrival: true,
      careGuide: 'Dry clean only. Store flat in garment bag.',
      blouseDetails: 'Heavy hand-embellished velvet front, back, and sleeve fabric included.',
    },
    {
      name: 'Gul-e-Dawood Dusty Rose Raw Silk Saree',
      slug: 'gul-e-dawood-dusty-rose-raw-silk-saree',
      description: 'Handspun raw silk in a muted dusty rose pink tint, featuring subtle self-weave checks, gold tissue borders, and dainty floral resham bootis. Ideal for Qawwali nights and Nikkah celebrations.',
      categorySlug: 'festive',
      price: 19500,
      discountPrice: 17500,
      colors: ['Pink', 'Gold'],
      fabric: 'Handspun Raw Silk',
      images: [
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 9,
      sku: 'RIV-RAW-006',
      featured: false,
      newArrival: true,
      careGuide: 'Dry clean recommended.',
      blouseDetails: '1.0 meter raw silk unstitched blouse fabric.',
    },
    {
      name: 'Subh-e-Bahar Pastel Peach Floral Chiffon Saree',
      slug: 'subh-e-bahar-pastel-peach-floral-chiffon-saree',
      description: 'Softest vintage peach chiffon with impressionist floral botanicals and delicate satin piping. Effortlessly breezy for day weddings, Sunday brunches, and festive lunches.',
      categorySlug: 'casual',
      price: 6800,
      discountPrice: 5900,
      colors: ['Pink', 'Beige'],
      fabric: 'Fine Printed Chiffon',
      images: [
        'https://images.unsplash.com/photo-1610030469668-935a8df2aef6?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 14,
      sku: 'RIV-CAS-007',
      featured: false,
      newArrival: false,
      careGuide: 'Hand wash gentle cold or dry clean. Low iron.',
      blouseDetails: 'Includes 0.85m matching peach crepe blouse piece.',
    },
    {
      name: 'Darya Sapphire Blue Handloom Brocade Saree',
      slug: 'darya-sapphire-blue-handloom-brocade-saree',
      description: 'Royal sapphire blue silk woven with metallic silver and gold meenakari motifs. A showstopper saree tailored for high-profile receptions and formal family galas.',
      categorySlug: 'wedding',
      price: 34000,
      discountPrice: 29500,
      colors: ['Blue', 'Gold'],
      fabric: 'Pure Handloom Brocade Silk',
      images: [
        'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 4,
      sku: 'RIV-BRO-008',
      featured: true,
      newArrival: false,
      careGuide: 'Strictly dry clean only.',
      blouseDetails: '1.0 meter contrast navy brocade fabric included.',
    },
    {
      name: 'Kashaf Plum Purple Resham Work Saree',
      slug: 'kashaf-plum-purple-resham-work-saree',
      description: 'Deep plum purple georgette saree lined with intricate Kashmiri resham flora and subtle mirror accents along the borders. Luxurious feel with comfortable all-evening drape.',
      categorySlug: 'party-wear',
      price: 15200,
      discountPrice: null,
      colors: ['Purple', 'Gold'],
      fabric: 'Flowing Silk Georgette',
      images: [
        'https://images.unsplash.com/photo-1610030470298-0c6f2a87895e?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 11,
      sku: 'RIV-GEO-009',
      featured: false,
      newArrival: true,
      careGuide: 'Dry clean only.',
      blouseDetails: '1m dyed purple silk blouse fabric.',
    },
    {
      name: 'Sitara Champagne Gold Metallic Tissue Saree',
      slug: 'sitara-champagne-gold-metallic-tissue-saree',
      description: 'Gleaming luminous spun tissue silk in pure champagne gold tone. Captures stage lighting mesmerisingly, making it a red-carpet favorite across Karachi & Lahore fashion circles.',
      categorySlug: 'party-wear',
      price: 17800,
      discountPrice: 15900,
      colors: ['Gold', 'Beige'],
      fabric: 'Lustrous Spun Metallic Tissue',
      images: [
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1583391733975-081014e7a83d?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 7,
      sku: 'RIV-TIS-010',
      featured: true,
      newArrival: false,
      careGuide: 'Dry clean only. Iron inside out on silk setting.',
      blouseDetails: 'Includes 1.0m matching tissue blouse piece.',
    },
    {
      name: 'Zartaj Olive Green Handloom Chanderi Saree',
      slug: 'zartaj-olive-green-handloom-chanderi-saree',
      description: 'Authentic Chanderi silk cotton weave in warm olive green with woven gold zari borders and geometric pallu. Breathable, crisp, and dignified for work and semi-formal wear.',
      categorySlug: 'work',
      price: 8800,
      discountPrice: null,
      colors: ['Green', 'Gold'],
      fabric: 'Handloom Chanderi Silk Cotton',
      images: [
        'https://images.unsplash.com/photo-1610030469668-935a8df2aef6?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 15,
      sku: 'RIV-WRK-011',
      featured: false,
      newArrival: false,
      careGuide: 'Gentle hand wash in mild shampoo or dry clean.',
      blouseDetails: '0.9 meter running blouse fabric included.',
    },
    {
      name: 'Kohsar Charcoal Slate Handwoven Linen Saree',
      slug: 'kohsar-charcoal-slate-handwoven-linen-saree',
      description: 'Refined 100-count organic linen in charcoal grey with slim silver zari borders. Perfect for working professionals, academic convocations, and executive meetings.',
      categorySlug: 'work',
      price: 6400,
      discountPrice: 5400,
      colors: ['Black', 'White', 'Other'],
      fabric: '100% Organic Linen',
      images: [
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 18,
      sku: 'RIV-LIN-012',
      featured: false,
      newArrival: false,
      careGuide: 'Gentle hand wash. Starch lightly if crisp drape is desired.',
      blouseDetails: '0.85m self-textured linen blouse piece included.',
    },
    {
      name: 'Shehr-e-Khaas Ruby Red Bridal Zardozi Couturier Saree',
      slug: 'shehr-e-khaas-ruby-red-bridal-zardozi-couturier-saree',
      description: 'The pinnacle of Pakistani bridal couture. Rich scarlet red katan silk adorned with authentic 24k gold plated dabka, naqshi, real pearls, and cut-work border. Worn by discerning brides across Lahore and London.',
      categorySlug: 'bridal',
      price: 92000,
      discountPrice: 84000,
      colors: ['Red', 'Maroon', 'Gold'],
      fabric: 'Heirloom Katan Silk & Net Overlay',
      images: [
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 2,
      sku: 'RIV-BRD-013',
      featured: true,
      newArrival: true,
      careGuide: 'Professional museum-grade dry clean only. Preserve in unbleached calico.',
      blouseDetails: 'Exquisitely hand-worked front, back, and sleeve fabric with sweetheart neckline markings.',
    },
    {
      name: 'Zehra Mustard Gold Gota Patti Festive Saree',
      slug: 'zehra-mustard-gold-gota-patti-festive-saree',
      description: 'Warm auspicious haldi mustard hue highlighted with intricate Jaipur & Multani gota patti handwork. Ideal for Mayun, Mehndi celebrations, and dholki nights.',
      categorySlug: 'festive',
      price: 13800,
      discountPrice: 11900,
      colors: ['Gold', 'Other'],
      fabric: 'Pure Georgette with Silk Border',
      images: [
        'https://images.unsplash.com/photo-1610030470298-0c6f2a87895e?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1610030469668-935a8df2aef6?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 10,
      sku: 'RIV-FES-014',
      featured: false,
      newArrival: true,
      careGuide: 'Dry clean only to protect gota metallic sheen.',
      blouseDetails: '1.0 meter contrast emerald green raw silk blouse included.',
    },
    {
      name: 'Chandni White Chikankari Lakhnavi Saree',
      slug: 'chandni-white-chikankari-lakhnavi-saree',
      description: 'Pure pristine white georgette intricately hand-embroidered with 32 authentic chikan stitches and delicate mukaish shimmer dots. Understated luxury that speaks volumes.',
      categorySlug: 'casual',
      price: 11500,
      discountPrice: null,
      colors: ['White', 'Beige'],
      fabric: 'Fine Cotton Georgette',
      images: [
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1583391733975-081014e7a83d?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 7,
      sku: 'RIV-CHK-015',
      featured: true,
      newArrival: false,
      careGuide: 'Dry clean recommended. Hand wash in cold water with gentle detergent.',
      blouseDetails: '1 meter embroidered georgette blouse fabric.',
    },
    {
      name: 'Aafreen Deep Teal Blue Mirror Work Saree',
      slug: 'aafreen-deep-teal-blue-mirror-work-saree',
      description: 'Sublime ocean teal blue chiffon adorned with real glass mirror work framed by delicate thread embroidery. Drapes with mesmerizing shimmer under ambient dinner candles.',
      categorySlug: 'party-wear',
      price: 14200,
      discountPrice: 12500,
      colors: ['Blue', 'Green'],
      fabric: 'Pure Chiffon with Mirror Accents',
      images: [
        'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 8,
      sku: 'RIV-PTY-016',
      featured: false,
      newArrival: true,
      careGuide: 'Dry clean only.',
      blouseDetails: '0.9m mirror worked sleeve and neck blouse fabric.',
    },
    {
      name: 'Malka-e-Bahar Coral Peach Satin Silk Saree',
      slug: 'malka-e-bahar-coral-peach-satin-silk-saree',
      description: 'Ultra-luxurious heavyweight Italian satin silk with a mirror-smooth liquid finish. Rendered in a flattering coral blush hue with minimalist French piping.',
      categorySlug: 'sale',
      price: 7500,
      discountPrice: 5200,
      colors: ['Pink', 'Beige'],
      fabric: 'Liquid Gloss Satin Silk',
      images: [
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1610030469668-935a8df2aef6?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 12,
      sku: 'RIV-SAL-017',
      featured: false,
      newArrival: false,
      careGuide: 'Dry clean only. Steam iron only.',
      blouseDetails: '1.0 meter heavy satin blouse fabric included.',
    },
    {
      name: 'Nilofer Sand Beige Organza Gilded Saree',
      slug: 'nilofer-sand-beige-organza-gilded-saree',
      description: 'Warm sandy beige sheer organza featuring hand-painted floral motifs outlined in gold metallic foil and finished with hand-knotted pearl tassels on the pallu.',
      categorySlug: 'festive',
      price: 21000,
      discountPrice: 18500,
      colors: ['Beige', 'Gold'],
      fabric: 'Fine Silk Organza',
      images: [
        'https://images.unsplash.com/photo-1583391733975-081014e7a83d?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 6,
      sku: 'RIV-ORG-018',
      featured: true,
      newArrival: true,
      careGuide: 'Gentle dry clean only.',
      blouseDetails: 'Includes 1 meter beige raw silk unstitched blouse.',
    },
    {
      name: 'Mehr-un-Nisa Royal Maroon Banarasi Jangla Saree',
      slug: 'mehr-un-nisa-royal-maroon-banarasi-jangla-saree',
      description: 'An archival reproduction of royal court sarees. Dense gold jangla weaving across rich claret maroon katan silk. A collector’s possession meant to be passed down generations.',
      categorySlug: 'luxury',
      price: 62000,
      discountPrice: 56000,
      colors: ['Maroon', 'Gold'],
      fabric: 'Pure Handloom Katan Silk',
      images: [
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1610030470298-0c6f2a87895e?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 4,
      sku: 'RIV-LUX-019',
      featured: true,
      newArrival: false,
      careGuide: 'Professional dry clean only. Wrap in unbleached cotton.',
      blouseDetails: '1.0 meter pure katan brocade blouse piece included.',
    },
    {
      name: 'Bahar-e-Nau Lavender Lilac Chiffon Saree',
      slug: 'bahar-e-nau-lavender-lilac-chiffon-saree',
      description: 'Soft whimsical lilac lavender chiffon with silver mukaish sparkles and baby pearl piping along the fall. Youthful, romantic, and perfectly weighted for easy drapes.',
      categorySlug: 'sale',
      price: 8900,
      discountPrice: 6800,
      colors: ['Purple', 'Other'],
      fabric: 'Pure Bamboo Chiffon',
      images: [
        'https://images.unsplash.com/photo-1610030469668-935a8df2aef6?auto=format&fit=crop&w=1000&q=85',
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85',
      ],
      stock: 9,
      sku: 'RIV-SAL-020',
      featured: false,
      newArrival: false,
      careGuide: 'Gentle dry clean.',
      blouseDetails: '0.85m matching lilac silk blouse piece.',
    },
  ];

  const createdProducts = [];
  for (const item of products) {
    const categoryId = createdCategories[item.categorySlug] || createdCategories['wedding'];
    const p = await prisma.product.create({
      data: {
        name: item.name,
        slug: item.slug,
        description: item.description,
        categoryId: categoryId,
        price: item.price,
        discountPrice: item.discountPrice,
        colors: JSON.stringify(item.colors),
        fabric: item.fabric,
        images: JSON.stringify(item.images),
        stock: item.stock,
        sku: item.sku,
        featured: item.featured,
        newArrival: item.newArrival,
        active: true,
        careGuide: item.careGuide,
        blouseDetails: item.blouseDetails,
      },
    });
    createdProducts.push(p);
  }

  console.log('--- Seeding Initial Orders ---');
  const sampleOrders = [
    {
      orderNumber: 'RIV-98241',
      userId: customer1.id,
      customerName: 'Ayesha Khan',
      customerEmail: 'ayesha.khan@example.com',
      customerPhone: '+92 321 9876543',
      shippingAddress: 'House 42, Street 15, Sector F-7/2',
      city: 'Islamabad',
      postalCode: '44000',
      items: [
        {
          productId: createdProducts[0].id,
          name: createdProducts[0].name,
          slug: createdProducts[0].slug,
          selectedColor: 'Maroon',
          price: 42000,
          quantity: 1,
          image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=600&q=80',
        },
      ],
      subtotal: 42000,
      shippingFee: 0, // Free above 15k
      total: 42000,
      paymentMethod: 'Cash on Delivery',
      status: 'Delivered',
      notes: 'Please ring bell twice upon arrival.',
    },
    {
      orderNumber: 'RIV-98242',
      userId: customer2.id,
      customerName: 'Mahnoor Tariq',
      customerEmail: 'mahnoor.tariq@example.com',
      customerPhone: '+92 333 4567890',
      shippingAddress: '28-C, Model Town Extension',
      city: 'Lahore',
      postalCode: '54700',
      items: [
        {
          productId: createdProducts[2].id,
          name: createdProducts[2].name,
          slug: createdProducts[2].slug,
          selectedColor: 'Black',
          price: 14500,
          quantity: 1,
          image: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=600&q=80',
        },
        {
          productId: createdProducts[6].id,
          name: createdProducts[6].name,
          slug: createdProducts[6].slug,
          selectedColor: 'Pink',
          price: 5900,
          quantity: 1,
          image: 'https://images.unsplash.com/photo-1610030469668-935a8df2aef6?auto=format&fit=crop&w=600&q=80',
        },
      ],
      subtotal: 20400,
      shippingFee: 0,
      total: 20400,
      paymentMethod: 'Cash on Delivery',
      status: 'Shipped',
      notes: 'Call before delivery.',
    },
    {
      orderNumber: 'RIV-98243',
      userId: null,
      customerName: 'Zainab Bilgrami',
      customerEmail: 'zainab.b@yahoo.com',
      customerPhone: '+92 300 8213456',
      shippingAddress: 'Apartment 5B, Creek Vistas, Phase 8, DHA',
      city: 'Karachi',
      postalCode: '75500',
      items: [
        {
          productId: createdProducts[4].id,
          name: createdProducts[4].name,
          slug: createdProducts[4].slug,
          selectedColor: 'Maroon',
          price: 78000,
          quantity: 1,
          image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=600&q=80',
        },
      ],
      subtotal: 78000,
      shippingFee: 0,
      total: 78000,
      paymentMethod: 'Cash on Delivery',
      status: 'Processing',
      notes: 'Bridal order for wedding next week.',
    },
    {
      orderNumber: 'RIV-98244',
      userId: null,
      customerName: 'Sadia Rehman',
      customerEmail: 'sadia.rehman@gmail.com',
      customerPhone: '+92 312 3456789',
      shippingAddress: 'House 112, Street 4, Cavalry Ground',
      city: 'Lahore',
      postalCode: '54000',
      items: [
        {
          productId: createdProducts[10].id,
          name: createdProducts[10].name,
          slug: createdProducts[10].slug,
          selectedColor: 'Green',
          price: 8800,
          quantity: 1,
          image: 'https://images.unsplash.com/photo-1610030469668-935a8df2aef6?auto=format&fit=crop&w=600&q=80',
        },
      ],
      subtotal: 8800,
      shippingFee: 350,
      total: 9150,
      paymentMethod: 'Cash on Delivery',
      status: 'Confirmed',
      notes: null,
    },
    {
      orderNumber: 'RIV-98245',
      userId: customer1.id,
      customerName: 'Ayesha Khan',
      customerEmail: 'ayesha.khan@example.com',
      customerPhone: '+92 321 9876543',
      shippingAddress: 'House 42, Street 15, Sector F-7/2',
      city: 'Islamabad',
      postalCode: '44000',
      items: [
        {
          productId: createdProducts[9].id,
          name: createdProducts[9].name,
          slug: createdProducts[9].slug,
          selectedColor: 'Gold',
          price: 15900,
          quantity: 1,
          image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80',
        },
      ],
      subtotal: 15900,
      shippingFee: 0,
      total: 15900,
      paymentMethod: 'Cash on Delivery',
      status: 'Pending',
      notes: 'Need evening delivery if possible.',
    },
  ];

  for (const ord of sampleOrders) {
    await prisma.order.create({
      data: {
        orderNumber: ord.orderNumber,
        userId: ord.userId,
        customerName: ord.customerName,
        customerEmail: ord.customerEmail,
        customerPhone: ord.customerPhone,
        shippingAddress: ord.shippingAddress,
        city: ord.city,
        postalCode: ord.postalCode,
        itemsJson: JSON.stringify(ord.items),
        subtotal: ord.subtotal,
        shippingFee: ord.shippingFee,
        total: ord.total,
        paymentMethod: ord.paymentMethod,
        status: ord.status,
        notes: ord.notes,
      },
    });
  }

  console.log('--- Seeding Completed Successfully! ---');
}

main()
  .catch((e) => {
    console.error('Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
